### ISSUE TITLE
FMS 17 Schedules not appearing on FMS ACE calendar

### ISSUE THREAD

**Issue by mr-scott** [soliantconsulting/fms-ace#16]
**Describe the bug**
None of the scheduled scripts on our FMS 17 server appear in the FMS ACE calendar.

**To Reproduce**
1. Login to FMS ACE at https://ourserver.com/fms-ace/ with known-good FMS Admin credentials
2. Current view displayed is "Weekly" with current day highlighted in pale yellow
3. Change view to Month or Day - still no scheduled FileMaker script events from our FMS 17
4. I can add "Verify Schedule" or "Add Message Schedule" events from within FMS ACE, — or add a "Backup Schedule" from the FMS Admin Console — and they do appear on the calendar as expected.

**Expected behavior**
I would expect to see our Scheduled FileMaker Server Scripts appear on the calendar

**Screenshots**
![image](https://user-images.githubusercontent.com/6674829/43484744-1465fd40-94c4-11e8-994d-32da9b00b95d.png)

![image](https://user-images.githubusercontent.com/6674829/43484762-20cd759a-94c4-11e8-9950-ba6322cde8d7.png)

![image](https://user-images.githubusercontent.com/6674829/43484778-2a0e3c34-94c4-11e8-85a0-f2493c8df5a7.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.13.6
 - Browser Safari
 - Version 11.1.2

**Server:**
Mac mini Server (Late 2012) - 2.6GHz Core I7
- OS: 10.13.6 (17G65)
- FMS: 17.0.2.203

**Comment by mjpineyro** [comment]
Thank you very much for the thorough description of the reported issue, and for including some screenshots.

I tried replicating the behavior that you described, by creating 2 FileMaker script schedules via the FAC (FileMaker Admin Console), and then trying to view them in the FMS ACE calendar. I did this in a host machine running 10.12.6 and 17.0.2.203, just like your environment. I used Safari 11.1.12 to launch ACE, the only difference being that I am on 10.12, and you reported being on 10.13.

I was not able to replicate what you described.

It's interesting that it's only FileMaker Script schedules that are now showing up in your copy of ACE. Would you be able to post another screenshot of the detailed settings of one of those 2 FMP Script schedules? I wonder if the combination of settings that you have chosen for those schedules, could be uncovering a bug in the code that we haven't run into thus far.

Now, you included a screenshot of the FM Script schedules in the FAC; can you confirm that you created those schedules via the FAC, and not via another means? I ask this because when you create schedules via the Admin API, you can set repeating settings for a schedule (for it to repeat every so many minutes or hours within a day, which is separate from the daily, weekly, etc frequency that you specify for the schedule). The repeatTask and repeatInterval API endpoint parameters cannot be specified from the FAC, and they are not supported in the current version of ACE. If you created those script schedules outside of the FAC and used those settings, that could be causing the issue you described.

Can you confirm what version of FMS ACE you are running? That should be displayed in the bottom left corner of the footer in the ACE app.

Finally, albeit unlikely that the following could be affecting this issue, let me ask:

a) are you using a custom or the default FMI certificate in your FMS?
b) can you replicate the issue when you use Firefox or Chrome instead of Safari?

**Comment by mr-scott** [comment]
> I did this in a host machine running 10.12.6 and 17.0.2.203, just like your environment. 

Thanks for the effort. I seem to have reported there server config incorrectly as being 10.2.6 when it's actually 10.13.6, just like my client FMPA 17 system. I updated the comment to reflect the change, and added some additional info about the server.

> I was not able to replicate what you described.

I apologize for the incorrect server OS version, and have edited the original comment with the updated configuration info. Perhaps the additional system configuration info I've added will assist you.

> It's interesting that it's only FileMaker Script schedules that are now showing up in your copy of ACE. Would you be able to post another screenshot of the detailed settings of one of those 2 FMP Script schedules? I wonder if the combination of settings that you have chosen for those schedules, could be uncovering a bug in the code that we haven't run into thus far.

![fms-17-scheduled-script-example---bcm](https://user-images.githubusercontent.com/6674829/43564477-cab7bb84-95db-11e8-9dc0-736a75c362c5.png)

> can you confirm that you created those schedules via the FAC, and not via another means? 

The Schedules were solely created within the FMS 17 Admin Console web page.

> Can you confirm what version of FMS ACE you are running? 

Yes…it is displayed as "FMS ACE v1.0.0-1-g1fe1f3d"

> a) are you using a custom or the default FMI certificate in your FMS?

We are not using the default certificate. I'm not certain of the criteria for what you refer to as a "custom" certificate.

> b) can you replicate the issue when you use Firefox or Chrome instead of Safari?

The issue persists in Safari [Version 11.1.2 (13605.3.8)], FireFox [61.0.1 (64-bit)], and Google Chrome [Version 67.0.3396.99 (Official Build) (64-bit)].

**Comment by mjpineyro** [comment]
Sorry for the delayed response here, I was not getting automated notifications for comments. Actually, Scott and I met at the FileMaker Developer Conference today, and we confirmed that the issue he reported affects FileMaker Script schedules that use the repeating option within a day, i.e. the "Every 1 Hours, 2:37 - 23:37" in the last screenshot uploaded. This is a feature not supported by the current version of ACE.

Please note that in my previous comment, I had stated that the repeatTask and repeatInterval API endpoint parameters cannot be specified from the FAC, and that was incorrect; these options can be specified via the FAC by choosing the "Between" option under "Time".

**Comment by mr-scott** [comment]
It appears that even Scheduled Server scripts created in the FileMaker Admin Console are not supported with FM ACE, so I will make a Feature Request, instead. Closing this Bug report.
